// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Usar variáveis de ambiente (obrigatórias)
// Configure as variáveis no arquivo .env na raiz do projeto
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Validação: garantir que variáveis de ambiente estão configuradas
if (!SUPABASE_URL) {
  throw new Error(
    '❌ VITE_SUPABASE_URL não configurada. ' +
    'Crie um arquivo .env na raiz do projeto com: VITE_SUPABASE_URL=https://seu-projeto.supabase.co'
  );
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    '❌ VITE_SUPABASE_ANON_KEY não configurada. ' +
    'Crie um arquivo .env na raiz do projeto com: VITE_SUPABASE_ANON_KEY=sua-chave-anon'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});