-- Identificar os 7 clientes que ainda faltam no banco
SELECT 
  key as client_key,
  split_part(key, '|', 1) as nome,
  split_part(key, '|', 2) as planner
FROM unnest(ARRAY[
  '#ref!|#ref!',
  'abner lucio aires schimidt|fabrício viana',
  'adenauer gonçalves da silva|felipe marques matias',
  'adilson luiz maciel de lara|diego perissinotto',
  'adilson pires cerveira junior|leonardo barroso',
  'adriana yumi kibe.|vinicius semeride francini',
  'adriano de oliveira neres ribeiro|#n/d',
  'adélia reis franco martins|abraão lima velozo',
  'afonso dutra rezende|mariana cruz',
  'agatha marcelino|marcelo ferreira rodrigues',
  'ageval rodrigues doria jr|emmanuel costa',
  'alan stefano dantas de paiva|diego perissinotto',
  'alana da fonseca jorge|raphael gonçalves teixeira',
  'alessandra christiane barboza santos|elisa cardoso',
  'alessandro henrique claro de souza|francine santos',
  'alessandro yuassa|laura galvão',
  'alex darlone de sousa|emmanuel costa',
  'alex lagacci|leonardo barroso',
  'alex renan almeida godoy|vinicius quinteiro',
  'alexander josé da silva|diego perissinotto',
  'alexandre dias guedes|diego perissinotto',
  'alexandre gabriel ferreira moreira serra|matheus lenci',
  'alexandre rodrigo soares|fabrício viana',
  'alexandre toebe gadelha|12',
  'alice roque gonçalves da cruz|felipe amorim',
  'aline cristina mariano marques|thiago cunha',
  'aline defensor amaral|diego perissinotto',
  'aline fonseca lima|francisco rivera',
  'aline gimenez graciano|wellington carvalho',
  'aline leonardo cunha|matheus lenci',
  'aline marciele marafon|raphael gonçalves teixeira',
  'aline rodrigues de almeida|gabriel baptista',
  'alisson pinheiro alves|bruna mantovani',
  'allan patrick silva|césar matos',
  'alveri roque patricio|abraão lima velozo',
  'amanda ambrozio de oliveira|francisco rivera',
  'amanda aparecida nabarro pereira|fernando bizelli',
  'amanda benjamim brighenti|marcelo ferreira rodrigues',
  'amanda da silva borges|mariana cruz',
  'amanda karen silva de almeida|laura galvão',
  'amanda martins story|leonardo rossetti',
  'amanda rezende gimenes|elisa cardoso',
  'amanda valente zambelli|francisco rivera',
  'amiraldo sampaio|murilo chiachio santiago',
  'ana beatriz paschoalato di nardo|joão pedro lotti jardim',
  'ana carolina almeida de matos|nathaliê melo',
  'ana carolina casseb pires|marcelo ferreira rodrigues',
  'ana carolina morais|raphael gonçalves teixeira',
  'ana carolina policarpo nascimento|emmanuel costa',
  'ana caroline rocha machado|murilo chiachio santiago',
  'ana cecília castanheira jardim|8',
  'ana clara mazer marques cavalheiro|murilo chiachio santiago',
  'ana claudia da silva nogueira|gustavo gomes da silva',
  'ana flávia fioroni lagacci|leonardo barroso',
  'ana kézia farias de souza lima|gabriel braga',
  'ana maria mantovani martinez|matheus lenci',
  'ana maria vieira|11',
  'ana paula a barboza|diego perissinotto',
  'ana paula costa de brito|maria vitória ferreira cotrim',
  'ana paula de moraes silva|diego perissinotto',
  'ana paula de ávila coutinho|francine santos',
  'ana paula galdeano cruz|joão leonardo thozzi',
  'ana paula martins das chagas|elisa cardoso',
  'ana paula pereira de sousa|andre luiz soares prezia',
  'ana paula venturini|raphael gonçalves teixeira',
  'ananda villela de oliveira|felipe youssef helal',
  'anderson rosa dos santos da paixão|leonardo barroso',
  'andrea calegari|6',
  'andrea doria|vinicius semeride francini',
  'andreia de melo porcari|murilo chiachio santiago',
  'andreia soares conceição|murilo chiachio santiago',
  'andressa caitano ribeiro|murilo chiachio santiago',
  'andressa ricardo de souza|felipe amorim',
  'andré bragagnoli scatolini|felipe youssef helal',
  'andré despontin malvezzi|marcelo ferreira rodrigues',
  'andré luis allan martins da silva|lucca de lauro',
  'andré luis patrício|abraão lima velozo',
  'andré navarro barros|felipe youssef helal',
  'andré tostes coelho|pedro ivo teixeira',
  'andréia marques costa|gustavo machado',
  'andrêyna da silva lima|wellington carvalho',
  'angela maria dos santos|joão leonardo thozzi',
  'angeline fuly|pedro ivo teixeira',
  'angelo daniel dagnoni fernandes|gabriel braga',
  'angélica souza de oliveira|hélio brollo junior',
  'anna carolina zamperlini|gustavo machado',
  'anna caroline leite costa|diego perissinotto',
  'anna luisa azambuja amaral|lucca de lauro',
  'anna vitória pinto camargo|lara assunção',
  'annelice martins da silva|mariana cruz',
  'antonio cassio vaz|emmanuel costa',
  'antônio genivaldo pereira do nascimento|gabriel braga',
  'argemiro mendes feitoa neto|emmanuel costa',
  'arian alecio de paula lima|rafael kanashiro',
  'arthur antolini tavares|gabriel cury',
  'arthur gabriel vasconcelos peres junior|marcelo ferreira rodrigues',
  'arthur machado minuzzi|marcelo ferreira rodrigues',
  'arthur souza duarte|emmanuel costa',
  'artur henrique de sousa santos|gabriel baptista',
  'artur moreno fonseca|gabriel baptista',
  'aryadne thaynara de souza gomes|marcelo ferreira rodrigues',
  'atena victor silva filomeno|matheus lenci',
  'augusto junior da luz ribeiro|francisco rivera',
  'augusto romano tinfre|bianca sara garcia onaga',
  'aurea adriana tiburcio patricio|abraão lima velozo',
  'barbara bueno silva|gustavo machado',
  'barbara de lima cicco|leonardo barroso',
  'barbara florindo moura|francine santos',
  'barbara stephanie soares de são joaquim|gustavo machado',
  'beatriz corrêa|elisa cardoso',
  'beatriz cunha braga|andre luiz soares prezia',
  'beatriz evangelista de santana|felipe marques matias',
  'beatriz hyppolito da justa|emmanuel costa',
  'beatriz mansur tertualiano|gabriel braga',
  'beatriz salandin dal pozzo|matheus okamura lopes',
  'beatriz sousa pinheiro|diego perissinotto',
  'bernardo de mattos fernandes|murilo chiachio santiago',
  'bernardo dias|laura galvão',
  'bethânia neves|pedro ivo teixeira',
  'bianca borges machado|wellington carvalho',
  'bianca do nascimento silva|raphael gonçalves teixeira',
  'bianca gomes barbosa de oliveira|elisa cardoso',
  'bianca nicoli wiegert|felipe youssef helal',
  'bianca silvestre barboza|fernando bizelli',
  'brenda freitas|maria vitória ferreira cotrim',
  'brenda gomes|felipe youssef helal',
  'brenda teles gama silva|raphael gonçalves teixeira',
  'breno de araujo ferreira|abraão lima velozo',
  'brisa albuquerque|gustavo machado',
  'bruna alvite nogueira gomes|bianca sara garcia onaga',
  'bruna aparecida lourenço gonçalves|gabriel baptista',
  'bruna de andrade nunes|mariana cruz',
  'bruna de freitas|gabriel cury',
  'bruna eduarda peres maciel castro|8',
  'bruna rafaeli bezerra de lima|emmanuel costa',
  'bruna rajão costa fernandes|leonardo barroso',
  'bruna ribeiro pimenta|mateus savietto',
  'bruna silva fernandes|pedro ivo teixeira',
  'bruno d''angelo trindade|matheus okamura lopes',
  'bruno dias del claro|lucca de lauro',
  'bruno henrique guizzo|felipe youssef helal',
  'bruno lopes|11',
  'bruno miguel ocanha|gustavo gomes da silva',
  'bruno nobrega moura|8',
  'bruno paes guimarães|pedro ivo teixeira',
  'bruno paulo alcassa|mariana cruz',
  'bruno pereira magalhães|gabriel baptista',
  'bruno ribeiro de oliveira|mateus savietto',
  'bruno valdecir de souza silva|emmanuel costa',
  'bruno vargas bücker|leonardo barroso',
  'bárbara estivalli gonçalves|francisco rivera',
  'bárbara miranda|elisa cardoso',
  'caio cesar garcia|gabriel felix',
  'caio della colleta vianna|gustavo gomes da silva',
  'caio diniz salles|raphael gonçalves teixeira',
  'caio francisco alves de lima|francine santos',
  'caio roman sant''anna|fernando bizelli',
  'camila bylaardt volker|nathaliê melo',
  'camila cooper|1',
  'camila de freitas|vinicius semeride francini',
  'camila goulart rodrigues|maria vitória ferreira cotrim',
  'camila jacob naviskas|francine santos',
  'camila yumi yatabe|12',
  'caren balestrin|murilo chiachio santiago',
  'carine de borba dias|wellington carvalho',
  'carine isabele da silva|abraão lima velozo',
  'carla dias de borba|fabrício viana',
  'carlos arthur fernandes sobreira|emmanuel costa',
  'carlos augusto de brito ribeiro|fernando bizelli',
  'carlos henrique cabral viana|fabrício viana',
  'carlos henrique magalhães|maria vitória ferreira cotrim',
  'carlos josé vieira|francisco rivera',
  'carlos machado da silva|fernando bizelli',
  'carlos renato dos anjos|francisco rivera',
  'carlos rene zuniga arqueja|matheus okamura lopes',
  'carlos vinícius alves da cruz barbosa|wellington carvalho',
  'carolina baldrati|raphael gonçalves teixeira',
  'carolina de carvalho duarte guimarães|gustavo gomes da silva',
  'carolina de queiroz telles antonucci|francine santos',
  'carolina fernanda gurgel|gustavo gomes da silva',
  'carolina marcucci aguiar|francisco rivera',
  'carolina rocha figueiredo da silva|gustavo machado',
  'carolina vecchi|gustavo machado',
  'caroline cristina beltrame silva|francisco rivera',
  'caroline eves saltarelli|matheus lenci',
  'caroline leite de andrade e silva|laura galvão',
  'caroline piagio da silva|felipe youssef helal',
  'caroline zaia de assis|elisa cardoso',
  'cecilia yuri takahashi|laura galvão',
  'celia yukie nose|francisco rivera',
  'celso mariano de souza|laura galvão',
  'cesar coelho graff|12',
  'cirenio josé da gama|5',
  'cirlene de santana cadima|bruna mantovani',
  'clara da rocha carvalhedo dos santos|emmanuel costa',
  'clara vittoria costa enéas|felipe youssef helal',
  'clarice kusma baisan fernandes|abraão lima velozo',
  'clarissa nunes alexandrino|diego perissinotto',
  'claudia brandão onaga|bianca sara garcia onaga',
  'claudia regina de souza brandão|6',
  'clayton de oliveira luz|raphael gonçalves teixeira',
  'cleyton john santana mendonça|abraão lima velozo',
  'clovis humberto dos santos|leonardo rossetti',
  'cláudia de carvalho palma|bianca sara garcia onaga',
  'cora sofia takaya paiva|pedro ivo teixeira',
  'cristiane da costa souza|14',
  'cristie yuri ochiai sassaki|laura galvão',
  'cristina careaga khabbaz|caio bragança',
  'cristina conceição baccaro|hélio brollo junior',
  'césar valentim da silva|matheus lenci',
  'daiana dos santos silva|felipe marques matias',
  'daiane aparecida monteiro barbosa elias|raphael gonçalves teixeira',
  'daiane bassetti|leonardo rossetti',
  'damasio willian da silva chagas|11',
  'dandara lyone silva de oliveira|maria vitória ferreira cotrim',
  'daniel augusto ribeiro pereira|gabriel cury',
  'daniel barcheta oliveira|fernando bizelli',
  'daniel henrique domeneguetti oliveira|lucca de lauro',
  'daniel imbassahy de sá bittencourt câmara e silva|joão pedro lotti jardim',
  'daniel lima da rocha leão|francine santos',
  'daniel rodrigues da silva|7',
  'daniel unt mazzer|abraão lima velozo',
  'daniela bianchini rosso|abraão lima velozo',
  'daniela campanholo|matheus okamura lopes',
  'daniela daniels|andre luiz soares prezia',
  'daniela de andrade pereira carrara|laura galvão',
  'daniela de lauro pavan pighini|lucca de lauro',
  'daniela maria thozzi|joão leonardo thozzi',
  'daniela marinho martins|13',
  'daniele oliveira da silva|felipe youssef helal',
  'danielle cristina ferreira machado|murilo chiachio santiago',
  'danilo dos santos neves|andre luiz soares prezia',
  'danilo pessoa cardoso|abraão lima velozo',
  'danrlei alves dos santos|11',
  'danylo vaz francisquini|fabrício viana',
  'davi felix calciolari|munir mustafa',
  'debora freitas jordan|césar matos',
  'deborah de lima cicco|leonardo barroso',
  'denilson rivail holmo|francisco rivera',
  'denis marcolino|leonardo barroso',
  'denis nicolau pereira correia|diego perissinotto',
  'diandra|vinicius quinteiro',
  'dianeglace alanna silva antunes|maria vitória ferreira cotrim',
  'diego de paula santos|mariana cruz',
  'diego heidmann|8',
  'diego montiel gundim|12',
  'diego vieira da silva|wellington carvalho',
  'diogo reis beltrao lessa|mariana cruz',
  'djalma baute filho|samuel teixeira',
  'douglas machado casceiro|thamires furlan',
  'douglas meira dos santos|wellington carvalho',
  'débora evelin sampaio menezes|gabriel braga',
  'débora garcia de souza|leonardo rossetti',
  'débora mello de almeida|11',
  'débora teraoka|emmanuel costa',
  'eber pereira da fonseca|abraão lima velozo',
  'edalmo de abreu vinhosa|leonardo rossetti',
  'eder luiz magnani|bruna mantovani',
  'ediemerson romualdo de souza maia|andre luiz soares prezia',
  'edilson da conceição moura junior|elisa cardoso',
  'edineia sofia favaro nunes|joão pedro lotti jardim',
  'edson cruz buosi|fernando bizelli',
  'eduarda hernandez|marcelo ferreira rodrigues',
  'eduardo bowen luz|gabriel baptista',
  'eduardo queiroz machado|murilo chiachio santiago',
  'edwilson rijo suguimoto|4',
  'eleneide cristina do nascimento gama|wellington carvalho',
  'eliana ayoub|caio bragança',
  'eliane lumi hashimoto|gabriel baptista',
  'elisa meira bastos|gustavo gomes da silva',
  'elisangela cardoso|diego perissinotto',
  'elizabete ribeiro isidoro|laura galvão',
  'elizeu victor gomes de melo|fabrício viana',
  'eliézer felipe bueno de oliveira|laura galvão',
  'elyan rafael vargas sander|maria vitória ferreira cotrim',
  'emanuel victor cordeiro da costa silva|emmanuel costa',
  'emilly caroliny rodrigues de sousa paes landim|elisa cardoso',
  'emily marinhos guedes dias|diego perissinotto',
  'eneida baccaro modonezi|hélio brollo junior',
  'enzo athayde cardoso costa|murilo chiachio santiago',
  'enzo augusto da maia|matheus lenci',
  'erica lima do nascimento|francine santos',
  'erika danielle gonçalves|elisa cardoso',
  'erika gerhardt barbosa|laura galvão',
  'ester de aguiar|raphael gonçalves teixeira',
  'evandro ornelas dos santos|felipe marques matias',
  'everson taco|francisco rivera',
  'everton soares de souza|pedro ivo teixeira',
  'evillyn dos santos lessa|diego perissinotto',
  'ezequiel gnich|wellington carvalho',
  'fabio hissashi akaishi|4',
  'fabio leonardo tomas|joão leonardo thozzi',
  'fabio luiz cortez ribeiro|murilo chiachio santiago',
  'fabio macedo da costa|elisa cardoso',
  'fabrício lopes|elisa cardoso',
  'fabrízia rossetti|2',
  'felipe bomfim de jesus da silva|francisco rivera',
  'felipe cagnani lima rodrigues|munir mustafa',
  'felipe de jesus gonçalves|elisa cardoso',
  'felipe generoso oliveira silva|fernando bizelli',
  'felipe kafrouni|leonardo rossetti',
  'felipe martinelli doretto|vinicius semeride francini',
  'fellipe franco do o|fernando bizelli',
  'fernanda alves monteiro|francine santos',
  'fernanda arias madureira|leonardo rossetti',
  'fernanda lima magnani|bruna mantovani',
  'fernanda mendes gaudie-ley lobato soares|raphael gonçalves teixeira',
  'fernanda muniz de sousa|bianca sara garcia onaga',
  'fernanda setti ulson de souza|thiago moreira maran',
  'fernanda simi ferreira jacob|diego perissinotto',
  'fernando antoniangelo souza serra|leonardo rossetti',
  'fernando augusto filocomo campanini|felipe youssef helal',
  'fernando augusto leal|felipe youssef helal',
  'fernando luís viana pereira|wellington carvalho',
  'fernando salgado penteado de castro|matheus okamura lopes',
  'fernando sergio bisca|murilo chiachio santiago',
  'fhilipi matheus junqueira campos carvalho|fabrício viana',
  'filipe villanova itacarambi|leonardo rossetti',
  'flávia vasques|15',
  'franciele bíscaro dias|mariana cruz',
  'franciele ogrodowski|francine santos',
  'francielly moreno gonçalves|wellington carvalho',
  'francisco dácio rodrigues farias filho|raphael gonçalves teixeira',
  'francisco sergio sales|gabriel baptista',
  'frederico antônio coura rocha|emmanuel costa',
  'fátima leci de sousa cunha|gabriel braga',
  'gabriel alcázar plácido teixeira|lucca de lauro',
  'gabriel alves barboza|thiago cunha',
  'gabriel alves costa santos|marcelo ferreira rodrigues',
  'gabriel bueno de melo serrano|gabriel bueno de melo serrano',
  'gabriel bueno|mateus savietto',
  'gabriel candolato de almeida|joão pedro lotti jardim',
  'gabriel carnio cosin|mateus savietto',
  'gabriel da silva marcolino|gabriel baptista',
  'gabriel de oliveira ferraz paulino|fernando bizelli',
  'gabriel dominato silva|vinicius quinteiro',
  'gabriel gustavo borges tiago|felipe youssef helal',
  'gabriel henrique de oliveira sangião|gabriel braga',
  'gabriel iozzi|murilo chiachio santiago',
  'gabriel luiz salomão|fabrício viana',
  'gabriel pinheiro|matheus lenci',
  'gabriel ribeiro silva|marcelo ferreira rodrigues',
  'gabriel rodrigues coelho|gabriel braga',
  'gabriel rodrigues vieira silva|gabriel baptista',
  'gabriela basilio umpierre|leonardo barroso',
  'gabriela bernardes ferreira|maria vitória ferreira cotrim',
  'gabriela bernardes martins peixoto|joão pedro lotti jardim',
  'gabriela correia barrence|fernando bizelli',
  'gabriela da silva higino|leonardo barroso',
  'gabriela damaceno pinheiro|gabriel bueno de melo serrano',
  'gabriela fernanda algarve|matheus okamura lopes',
  'gabriela maria cursino da silva|bianca sara garcia onaga',
  'gabriela neiva de souza e silva|murilo chiachio santiago',
  'gabriela ramos guimarães lage|gustavo machado',
  'gabriela rodrigues lapér|gustavo gomes da silva',
  'gabriela sala benatti|murilo chiachio santiago',
  'gabriela schaefer|#n/d',
  'gabriele bortolotto cunha|21',
  'gabriele paoli dalla pozza|fabrício viana',
  'gabriella lima leal|nathaliê melo',
  'geisi ferreira marine oliveira|felipe marques matias',
  'geisiane silva araújo|leonardo barroso',
  'geissiane cardoso|abraão lima velozo',
  'gesliane sara vieira chaves|raphael gonçalves teixeira',
  'geórgia linhares cavalcante|gustavo gomes da silva',
  'giovani alves ribeiro|caio bragança',
  'giovani da silva martins alves|diego perissinotto',
  'giovanna costacurta cavalcante|wellington carvalho',
  'giovanni bruno gentil|#n/d',
  'giovanni italo zaneti cortizo borgia|12',
  'gisela do amaral boeno|andre luiz soares prezia',
  'gisele alvarenga sanches|bianca sara garcia onaga',
  'giulia ottoni de melo lopes|lucca de lauro',
  'giulle do nascimento e silva|andre luiz soares prezia',
  'glaucia teixeira|mariana cruz',
  'gleice santos meneses|bianca sara garcia onaga',
  'grazielli arcanjo bayer|gabriel baptista',
  'guilherme andraos sidrim|mariana cruz',
  'guilherme de oliveira cardoso|lucca de lauro',
  'guilherme defante telles|murilo chiachio santiago',
  'guilherme do val toledo prado|caio bragança',
  'guilherme henrique ikeda|fabrício viana',
  'guilherme nascimento|gabriel baptista',
  'guilherme pereira correa|fernando bizelli',
  'guilherme reikdal kallaur|gabriel cury',
  'guilherme ribeiro wagner|pedro ivo teixeira',
  'guilherme silva ribeiro|francisco rivera',
  'guilherme vinicius silva neto|francisco rivera',
  'gustavo cenci peters|11',
  'gustavo gomes vilas boas|5',
  'gustavo laiatti notaro|raphael gonçalves teixeira',
  'gustavo lemos gonçalves soares|gustavo gomes da silva',
  'gustavo marques de florio|andre luiz soares prezia',
  'gustavo vicente de brito catelani|bianca sara garcia onaga',
  'gustavo zancheta da silva|marcelo ferreira rodrigues',
  'hareton rubens da silva|emmanuel costa',
  'heitor eduardo lixandrão|matheus lenci',
  'helena ferraz chinelato|diego perissinotto',
  'helena rubianes lopes|lucca de lauro',
  'hellen amaral de oliveira teixeira|raphael gonçalves teixeira',
  'hellen anastacia de souza salvado|leonardo barroso',
  'heloisa verona sete rocha|thiago cunha',
  'henrique barros lopes|fabrício viana',
  'henrique brax vicensoto|joão pedro lotti jardim',
  'henrique pereira pinto|diego perissinotto',
  'henrique puia pelegrino|laura galvão',
  'henrique tortele dos santos|leonardo rossetti',
  'hertz vanderlei maceu|felipe youssef helal',
  'heráclito henrique santana lopes|wellington carvalho',
  'huziel ramos souto|laura galvão',
  'igor carlos dueti vilalba souza de abreu|caio bragança',
  'igor henrique farias lima|fernando bizelli',
  'igor ken kamigashima|munir mustafa',
  'igor martins pereira|pedro ivo teixeira',
  'igor storck da silva|elisa cardoso',
  'indra lutfi viana cairo|emmanuel costa',
  'ingred duarte hananias|thiago cunha',
  'ingrede eduarda muniz azevedo|raphael gonçalves teixeira',
  'ingrid figueiredo bittencourt|não',
  'ingrid viana da silva|mariana cruz',
  'isabela ferreira cortese|lucca de lauro',
  'isabela ferreira feitoza|mariana cruz',
  'isabela scaravelli romanatto|felipe youssef helal',
  'isabela setta|12',
  'isabela velardi gaspar|mariana cruz',
  'isabella braga tinoco da silva|marcelo ferreira rodrigues',
  'isabella gomes manetta|francisco rivera',
  'isabella sartori|5',
  'isabelle conde franco|mariana cruz',
  'isabelle daros pignot|gabriel bueno de melo serrano',
  'isabelle vera mendez pereira|laura galvão',
  'isadora maria policarpo lacerda|emmanuel costa',
  'isadora minuzzi|diego perissinotto',
  'israel manzoni souza|leonardo barroso',
  'italo antonio rodrigues nascimento de azeredo|elisa cardoso',
  'ivan emanuel toledo vásquez|felipe youssef helal',
  'ivan lendel feldkirche|murilo chiachio santiago',
  'ivanei carlos martins da silveira|gabriel baptista',
  'ivonete cristina da silva|diego perissinotto',
  'iza luana de oliveira trajano|emmanuel costa',
  'izabel campos mesquita|bianca sara garcia onaga',
  'izabeli martins alves nunes|nathaliê melo',
  'izabella alves barbosa cunto|leonardo barroso',
  'izabella ferreira rodrigues|marcelo ferreira rodrigues',
  'jaddy reisler|francisco rivera',
  'jamilly castro|pedro ivo teixeira',
  'janaina almeida do carmo|felipe marques matias',
  'janaina vieira|matheus okamura lopes',
  'janice rocha de assis|wellington carvalho',
  'jaqueline de souza paes|wellington carvalho',
  'jeanderson luiz mendes da silva|12',
  'jeniffer sthephani santana mimoria|mariana cruz',
  'jessica amorim do prado|marcelo ferreira rodrigues',
  'jessica de bosi e araujo|bianca sara garcia onaga',
  'jessica maira galvani da silva|gabriel baptista',
  'jheniffer leodoro|gabriel braga',
  'jhonatan de souza romualdo|marcelo ferreira rodrigues',
  'jhonatan vinícius silva de lima|thiago cunha',
  'joacy severina souza soares|matheus lenci',
  'joana pinheiro da silva|raphael gonçalves teixeira',
  'joane mara maia conte|vinicius semeride francini',
  'joao guilherme braga dos santos silva|diego perissinotto',
  'jocimar de oliveira alves filho|gabriel baptista',
  'joelson isidoro|laura galvão',
  'john victor ferreira alves|vinicius quinteiro',
  'jonas bezerra da silva|laura galvão',
  'jonatan agostinho da silva|murilo chiachio santiago',
  'jonathan afonso lobato pinto|maria vitória ferreira cotrim',
  'jonathan henrique pereira geraldo|2',
  'jonathan lima julio|abraão lima velozo',
  'jordana maria pinheiro de souza|gabriel braga',
  'jorgeane silva santana|pedro ivo teixeira',
  'josimar pellin|leonardo barroso',
  'josué de jesus da silva|gabriel braga',
  'josé bezerra filho|laura galvão',
  'josé eduardo augusto couto fontes|francisco rivera',
  'josé eduardo russo peris|4',
  'josé edvaldo caetano de freitas júnior|maria vitória ferreira cotrim',
  'josé fernando pavan|lucca de lauro',
  'josé ricardo felipe de oliveira|felipe youssef helal',
  'josé roberto guimarães barros neto|lucca de lauro',
  'joão gabriel de carvalho ferreira|raphael gonçalves teixeira',
  'joão gabriel saback de araújo|joão pedro lotti jardim',
  'joão izack sales coelho|matheus okamura lopes',
  'joão paulo vigneron alves|pedro ivo teixeira',
  'joão pedro batistão fallani|pedro ivo teixeira',
  'joão pedro carvalho silva|elisa cardoso',
  'joão pedro chiacchio félix|felipe youssef helal',
  'joão pedro quaranta de almeida|elisa cardoso',
  'joão pedro ronconi|gustavo machado',
  'joão victor augusto hachich|gustavo gomes da silva',
  'joão victor dias costa|emmanuel costa',
  'joão victor dos santos lanzellotti|raphael gonçalves teixeira',
  'joão victor fernandes da silva|9',
  'joão vinicius da silva carvalho|emmanuel costa',
  'joão vitor de souza andrade|5',
  'joão vitor santos julio|abraão lima velozo',
  'juan andres iglesias junior|emmanuel costa',
  'jucicleia marília nery de castro|gabriel bueno de melo serrano',
  'jucielio asevedo silva|murilo chiachio santiago',
  'julia aparecida de oliveira araujo|francisco rivera',
  'julia carolina ramiro dos santos|diego perissinotto',
  'julia ciuldim caseri|samuel teixeira',
  'julia de almeida catarino pereira|andre luiz soares prezia',
  'julia de campos gonçalves|césar matos',
  'julia duarte melo|vinicius quinteiro',
  'julia maria fontão oliveira|lucca de lauro',
  'julia mattos fedozzi|mariana cruz',
  'juliana alves luiz pereira|leonardo rossetti',
  'juliana araújo marques|raphael gonçalves teixeira',
  'juliana de pieri coelho|gustavo machado',
  'juliana gasparini|bruna mantovani',
  'juliana gonçalves da costa teixeira|césar matos',
  'juliana shimabuk|wellington carvalho',
  'juliana souza freitas|felipe marques matias',
  'juliano fabri|lucca de lauro',
  'juliano pereira duarte|felipe youssef helal',
  'junia fontes vieira cidade|caio bragança',
  'jéssica beatriz tolare|maria vitória ferreira cotrim',
  'jéssica lemes siqueira|gustavo machado',
  'jéssica schiavo|hélio brollo junior',
  'júlia barreto carvalho paim de morais|hélio brollo junior',
  'júlia maria soares da silva|emmanuel costa',
  'júlio de sousa vendramini|pedro ivo teixeira',
  'kaemily lemes colla pellin|leonardo barroso',
  'kalil altiele moraes|murilo chiachio santiago',
  'kamila cotti castro|andre luiz soares prezia',
  'kamile danielle de souza machado|elisa cardoso',
  'karen cristina de araújo ornelas|felipe marques matias',
  'karen giulia rodrigues|matheus okamura lopes',
  'karen ito kawagoe|bruna mantovani',
  'karina muniz viana|fabrício viana',
  'karoline barbosa rodrigues|matheus lenci',
  'karoline costa ferreira|fernando bizelli',
  'karolyna magalhães batista|andre luiz soares prezia',
  'katia camila de re|matheus okamura lopes',
  'kawana majori dos santos|matheus okamura lopes',
  'kazuyuki kadota|lucca de lauro',
  'keila brilhante gonçalves cardoso|laura galvão',
  'keila cristina dias franca heidmann|wellington carvalho',
  'keila ferreira baraúna|gabriel braga',
  'kennedy da silva santos|andre luiz soares prezia',
  'keylla aguiar dos santos|vinicius quinteiro',
  'kirley farias|elisa cardoso',
  'kunio ochiai|laura galvão',
  'kédima kelly valiente de oliveira|francisco rivera',
  'lais carvalho|bruna mantovani',
  'lais rodrigues rocha|leonardo rossetti',
  'lais rosa nagai|matheus okamura lopes',
  'lara de sousa candemil|leonardo barroso',
  'lara gabrielly de lima|mariana cruz',
  'larissa amadeu|fernando bizelli',
  'larissa cerqueira cortez|mariana cruz',
  'larissa dias coutinho|raphael gonçalves teixeira',
  'larissa gonçalves castro de sá|gabriel cury',
  'larissa laís schutt|diego perissinotto',
  'larissa muniz matias|vinicius semeride francini',
  'laura catarine dueti vilalba souza de abreu|marcelo ferreira rodrigues',
  'laura de oliveira ferreira guedelha coutinho|5',
  'laura rios moreira|gabriel braga',
  'laura tamiris correa bertolucci|joão pedro lotti jardim',
  'lavínia caroline cardoso moreira|andre luiz soares prezia',
  'layenne emmanuelle pereira silva|gabriel baptista',
  'layza cristina quirino|abraão lima velozo',
  'laís valeria de oliveira santana|lara assunção',
  'lean pampana basoli|1',
  'leandro alves reis|wellington carvalho',
  'leandro roberto gois soares|matheus lenci',
  'leonardo alexandre ferreira silva|francine santos',
  'leonardo backy caleffi|wellington carvalho',
  'leonardo brunheroto redondano|vinicius quinteiro',
  'leonardo leite moura de matos|bianca sara garcia onaga',
  'leonardo reis lima da silva|francine santos',
  'leonardo ribeiro de morais|andre luiz soares prezia',
  'leonardo wiliam lopes|joão pedro lotti jardim',
  'lethicia cintra maura|gustavo gomes da silva',
  'leticia fick pereira da silva|matheus okamura lopes',
  'leticia freitas rafael|andre luiz soares prezia',
  'leticia lais bianchini|mariana cruz',
  'leticia zillo vanin|rafael kanashiro',
  'letícia cristina silvério|marcelo ferreira rodrigues',
  'letícia dias jordão teixeira|mariana cruz',
  'letícia dos santos chaves|diego perissinotto',
  'letícia fonseca mendes da silva|gabriel baptista',
  'letícia harumi hassegawa|laura galvão',
  'letícia kanasiro|raphael gonçalves teixeira',
  'leíse priscila gomes de oliveira|raphael gonçalves teixeira',
  'libiane de jesus sousa soares|gabriel braga',
  'ligia mello barbosa|leonardo rossetti',
  'lilian cristina moutinho da silveira|gabriel baptista',
  'lilian rocha da silva|diego perissinotto',
  'lise mariane moura de sousa|joão pedro lotti jardim',
  'livia caus|francine santos',
  'livia de faria terra|wellington carvalho',
  'livia lopes lozano|caio bragança',
  'livia martins sandoval|matheus lenci',
  'liziane neves michel|mariana cruz',
  'loren d angelo|francisco rivera',
  'lorena bendazolli leme|mariana cruz',
  'lorena carolina de oliveira patrício|abraão lima velozo',
  'luan honório dos santos|joão pedro lotti jardim',
  'luana lopes de souza|raphael gonçalves teixeira',
  'luana suguimoto barbero|francine santos',
  'luana vieira godoy|felipe youssef helal',
  'luara sá trovo|joão pedro lotti jardim',
  'lucas bindi|mariana cruz',
  'lucas calegari borelli|9',
  'lucas cova|gabriel baptista',
  'lucas de jesus ferreira|laura galvão',
  'lucas dos santos da silva|bianca sara garcia onaga',
  'lucas ferreira do amaral|alisson maciel',
  'lucas gabriel rezende pereira|andre luiz soares prezia',
  'lucas keuffer rettelbusch prado kizan|andre luiz soares prezia',
  'lucas lima da silva|andre luiz soares prezia',
  'lucas maciel domingues|mariana cruz',
  'lucas paulino comparini|9',
  'lucas pedrozo vasconcellos|lucca de lauro',
  'lucas reis|maria vitória ferreira cotrim',
  'lucas scandiuzzi|11',
  'lucas teixeira fernandes|fernando bizelli',
  'lucas yoshio tosta ida|césar matos',
  'luciana pero occhipinti|francisco rivera',
  'luciano alves corrêa|4',
  'lucidalva frança rossetti|leonardo rossetti',
  'lucifran lima carvalho|emmanuel costa',
  'ludmila medeiros kreuz|leonardo barroso',
  'ludmila rodrigues|abraão lima velozo',
  'luigi crivelaro bezzon|lucca de lauro',
  'luis eduardo patrício|abraão lima velozo',
  'luis fernando lovatto|marcelo ferreira rodrigues',
  'luis henrique geremias do nascimento|marcelo ferreira rodrigues',
  'luisa freitas colafati|andre luiz soares prezia',
  'luisa rodrigues polese freitas|leonardo rossetti',
  'luiz antonio buffolo|murilo chiachio santiago',
  'luiz cesar pinheiro de oliveira|abraão lima velozo',
  'luiz de oliveira araújo|lara assunção',
  'luiz felipe pedrassolli calixto|fernando bizelli',
  'luiz paulo bizelli junior|fernando bizelli',
  'luiza de almeida soares|bianca sara garcia onaga',
  'luiza hurtado patrus ananias|andre luiz soares prezia',
  'luís felipe carvalho correa de souza|francine santos',
  'luís felipe fernandes reiter|matheus lenci',
  'léo kortz vilas boas|fabrício viana',
  'lúcio flavio da silva godoi|thiago cunha',
  'madelene ribeiro queiroz|francisco rivera',
  'maiara rodrigues aguiar|leonardo barroso',
  'maiara santos vieira|lucca de lauro',
  'makcian alves martins|abraão lima velozo',
  'mallena lima de figuerêdo silva|mariana cruz',
  'marcela burrattino|12',
  'marcela oliveira de assunção|lara assunção',
  'marcelo cardoso ferreira|laura galvão',
  'marcelo conilho abrantes|lucca de lauro',
  'marcelo de arruda faber|gabriel bueno de melo serrano',
  'marcelo henrique carrara|laura galvão',
  'marcelo hissé das neves costa|murilo chiachio santiago',
  'marcelo padilha da costa|joão pedro lotti jardim',
  'marcia de fátima escórcio|leonardo rossetti',
  'marcia moussallem|bianca sara garcia onaga',
  'marcio carvalho|1',
  'marco antonio da santa cruz prestes|diego perissinotto',
  'marco antonio ribeiro novais|wellington carvalho',
  'marcos donizete da silva|mariana cruz',
  'marcos gimenes|elisa cardoso',
  'marcos paulo fermino frança|wellington carvalho',
  'marcos paulo sarges rolim|diego perissinotto',
  'marcos urbani|joão pedro lotti jardim',
  'marcos vinicios vieira dantas|emmanuel costa',
  'marcos vinícius modenezi|leonardo barroso',
  'marcus vinicius bernardi|fernando bizelli',
  'marcus vinicius janzkovski lopes|laura galvão',
  'marcus vinícius turati|joão pedro lotti jardim',
  'maria angélica xavier fazolin|rafael kanashiro',
  'maria aparecida gonçalves|gabriel baptista',
  'maria auxiliadora taveira lopes|bianca sara garcia onaga',
  'maria carolinna de albuquerque belo|diego perissinotto',
  'maria claudia araujo ferreira|elisa cardoso',
  'maria cristina de santana melo|mariana cruz',
  'maria eduarda fernandes de oliveira|lara assunção',
  'maria elisabete machado dos santos|matheus lenci',
  'maria elizabeth miranda villaça gentil|raphael gonçalves teixeira',
  'maria fernanda monteiro de aguiar|gabriel baptista',
  'maria luisa tidei piacenti dos santos|rafael kanashiro',
  'maria luiza spalla|munir mustafa',
  'maria nubileuda dos santos|gabriel braga',
  'maria nubineuda dos santos|gabriel braga',
  'maria paula bueno martinelli|matheus lenci',
  'maria paula elis medeiros quatrini|11',
  'maria raquel bueno ramos|raphael gonçalves teixeira',
  'maria tamiris da silva alves|fernando bizelli',
  'mariana barbosa de oliveira|2',
  'mariana gonçalves las casas|gustavo machado',
  'mariana maia diaz|rafael kanashiro',
  'mariana patelli juliani de souza lima|gabriel cury',
  'mariana scatolin rossafa garcia|elisa cardoso',
  'mariana soares lima|laura galvão',
  'marianna cabral de jesus|gabriel cury',
  'mariel carvalho gavioli vidal|vinicius quinteiro',
  'marilene silva martins|elisa cardoso',
  'marina barbosa pinto|andre luiz soares prezia',
  'marina de oliveira migotto|nathaliê melo',
  'marina gouvêa malheiros|matheus okamura lopes',
  'marina passos seixas|raphael gonçalves teixeira',
  'marina ramos silva guardia|matheus lenci',
  'marina zillo vanin ferrarezi|rafael kanashiro',
  'mary ohira ochiai|laura galvão',
  'masayuki andré tamanaha|pedro ivo teixeira',
  'mateus correia rodrigues|abraão lima velozo',
  'mateus da silva machado|marcelo ferreira rodrigues',
  'mateus pimentel loschi|mariana cruz',
  'matheus augusto stiegelmeier|maria vitória ferreira cotrim',
  'matheus carvalhedo dos santos|emmanuel costa',
  'matheus da cunha rodrigues|abraão lima velozo',
  'matheus domiciano gouveia|felipe youssef helal',
  'matheus henrique maceu|raphael gonçalves teixeira',
  'matheus santiago de melo barbosa|1',
  'matheus santos amorim|francisco rivera',
  'matheus silva batista|laura galvão',
  'mauro peghin junior|leonardo barroso',
  'maurício de oliveira|francisco rivera',
  'maximilham brandão de souza fermino|wellington carvalho',
  'maxwell salvador dos santos vieira|diego perissinotto',
  'maxwilliam domingues da silva lima|diego perissinotto',
  'mayara flores|elisa cardoso',
  'mayara henrique silva|leonardo rossetti',
  'mayara nadine do nascimento moraes|francine santos',
  'mayris da silva|felipe marques matias',
  'michael ribeiro de oliveira|matheus okamura lopes',
  'michele labiapari rodrigues|fernando bizelli',
  'michelle siewert|mateus savietto',
  'milena cianci buck|bruna mantovani',
  'milleny sabrini marcilio|10',
  'mirella marson lenzi|matheus okamura lopes',
  'mirian santos barbosa|francisco rivera',
  'moama silva moysés|gabriel baptista',
  'moisés nicolau stacke|diego perissinotto',
  'monica olinda de magalhaes barros|fabrício viana',
  'monique anacleto bueno|diego perissinotto',
  'monique fernandes de sousa yamaoka|elisa cardoso',
  'monique laura de oliveira|felipe youssef helal',
  'monize vicentina de souza|felipe youssef helal',
  'murilo alvarenga oliveira|felipe marques matias',
  'murilo mendes latorre soares|4',
  'myrelly karyane passos melnixenco|francine santos',
  'myure iamani de castro cardoso|raphael gonçalves teixeira',
  'márcia damasceno pena|6',
  'márcio faustini modonezi|hélio brollo junior',
  'mônica de souza|leonardo rossetti',
  'mônica oliveira de vasconselos|12',
  'mônica oliveira ferreira|abraão lima velozo',
  'naate dandara de sousa paiva|diego perissinotto',
  'naiara gomes de melo|fabrício viana',
  'nara froes de aguilar giocondo|gustavo machado',
  'nathalie guzman lugones quesada salies|matheus lenci',
  'nathan silva badu dos santos|elisa cardoso',
  'nathália sawitzki castilhos|maria vitória ferreira cotrim',
  'natália de paula silva oliveira|matheus lenci',
  'nery peres junior|murilo chiachio santiago',
  'nicolas da costa oliveira|caio bragança',
  'nicolas ignácio bueno|marcelo ferreira rodrigues',
  'nicolas pinto|mateus savietto',
  'nicole goes gomes|andre luiz soares prezia',
  'nicole ross de santiago|elisa cardoso',
  'niqui malheiros lang|felipe youssef helal',
  'nátaly enne da costa gonçalo|matheus lenci',
  'náthaly de matos souza|mariana cruz',
  'núbia nicoli turchiello|diego perissinotto',
  'olivia moraes ruberti|murilo chiachio santiago',
  'otavio saraiva xavier|mariana cruz',
  'otávio souza rocha|lucca de lauro',
  'pablo gabriel assis cavalheiro|murilo chiachio santiago',
  'paloma bueno de carvalho venâncio cardoso|mariana cruz',
  'paloma de araújo amaro|joão pedro lotti jardim',
  'paola pacheco|leonardo barroso',
  'paola taynnara gomes nogueira|gabriel baptista',
  'patricia amalia bentes salgado|10',
  'patricia keiko gonçalves|16',
  'patrícia daniela da costa scatolini|felipe youssef helal',
  'patrícia maria pessoa de melo martins|andre luiz soares prezia',
  'patrícia regina infanger campos|caio bragança',
  'paula souza rusticci|leonardo rossetti',
  'paulo césar melo matos|césar matos',
  'paulo henrique martinelli de oliveira|nathaliê melo',
  'paulo procopio de araujo ferraz|5',
  'paulo ricardo souza da silva|francisco rivera',
  'paulo roberto ignacio cardoso|gustavo machado',
  'paulo sergio xavier barbosa|wellington carvalho',
  'pedro antônio pagan bonaldo|matheus okamura lopes',
  'pedro carpinelli peixe|francisco rivera',
  'pedro henrique garcia romero|vinicius semeride francini',
  'pedro henrique moreira tostes|marcelo ferreira rodrigues',
  'pedro henrique naressi machado|gustavo machado',
  'pedro henrique rondina correa|caio bragança',
  'pedro henrique zamoro dos santos|gabriel baptista',
  'pedro herique archangelo|joão leonardo thozzi',
  'pedro ivo adegas silva|marcelo ferreira rodrigues',
  'pedro luis castro de carvalho|andre luiz soares prezia',
  'pedro ruffin pinhel|vinicius semeride francini',
  'plinio marcio braz|marcelo ferreira rodrigues',
  'priscila lopes molin|raphael gonçalves teixeira',
  'priscila pires|elisa cardoso',
  'priscila ribeiro leles araujo|diego perissinotto',
  'priscilla de fátima ribeiro balbino|gabriel bueno de melo serrano',
  'pâmella lauro|bruna mantovani',
  'rafael amano paes de barros|césar matos',
  'rafael bertolucci dias|#n/d',
  'rafael braghieri menillo|matheus okamura lopes',
  'rafael breda duarte diniz de moraes|leonardo rossetti',
  'rafael bruno matias de souza|leonardo rossetti',
  'rafael de oliveira pereira correia|felipe amorim',
  'rafael fernandes de sousa|andre luiz soares prezia',
  'rafael jhone coimbra pereira|5',
  'rafael nazarian szymonek|diego perissinotto',
  'rafaela cristina rodrigues da silva|lucca de lauro',
  'rafaela feijo do amaral|mariana cruz',
  'rafaela sanchez de camargo neves|andre luiz soares prezia',
  'rafaella bonassi dos santos|francisco rivera',
  'rafael niche de souza|laura galvão',
  'rannier pinheiro de souza|leonardo barroso',
  'raphael moreira silva|raphael gonçalves teixeira',
  'raphaela marsaioli gonçalves|12',
  'raquel maria chagas do amaral|lucca de lauro',
  'raquel satie yamaki kourroski|elisa cardoso',
  'raul fernando dias doria|vinicius semeride francini',
  'raul vargas boechat|marcelo ferreira rodrigues',
  'ravena seida tavares de melo|bianca sara garcia onaga',
  'rayhanna fernandes de souza oliveira|gustavo gomes da silva',
  'rebeca de queiroz dantas|mariana cruz',
  'rebeca moraes de oliveira|laura galvão',
  'regina cecília oliveira setti|gustavo gomes da silva',
  'regina costa silva|gustavo machado',
  'reinaldo francisco da silva|vinicius quinteiro',
  'renan andrade pereira|bruna mantovani',
  'renan augusto de oliveira|leonardo barroso',
  'renan calanca campregher|diego perissinotto',
  'renan gomes sarmento|9',
  'renan mendes de menezes|leonardo barroso',
  'renan rozada|matheus okamura lopes',
  'renata aparecida alves pelegrino|laura galvão',
  'renata dorrio mesquita teixeira gomes|felipe youssef helal',
  'renata frança marangone|fabrício viana',
  'renata galvão silva|laura galvão',
  'renata guise soares de azevedo harada|nathaliê melo',
  'renata matioli covre|nathaliê melo',
  'renata pereira façanha|mariana cruz',
  'renata simplício xavier|raphael gonçalves teixeira',
  'renato antonio silva risardi|murilo chiachio santiago',
  'renato barros dos santos|césar matos',
  'renato munhoz|elisa cardoso',
  'ricardo bertuccio silva|bruna mantovani',
  'ricardo de carvalho|fernando bizelli',
  'ricardo hideyuki t. ito|munir mustafa',
  'ricardo tetsuro sassaki|laura galvão',
  'rita de cássia ribeiro nunes|thiago moreira maran',
  'roberta sotto oyan|emmanuel costa',
  'roberto eufrasio da silva junior|leonardo rossetti',
  'roberto flávio pereira dos santos|fernando bizelli',
  'roberto luiz de oliveira|francine santos',
  'roberto pighini filho|lucca de lauro',
  'roberto pighini|13',
  'roberto savio ragazini|bianca sara garcia onaga',
  'robison gonçalves tesini|gustavo gomes da silva',
  'rodolfo bueno de souza|gabriel bueno de melo serrano',
  'rodolfo damasceno da silva|raphael gonçalves teixeira',
  'rodolpho bueno|diego perissinotto',
  'rodrigo ariedi kice|murilo chiachio santiago',
  'rodrigo brazão gonçalves de lima|francisco rivera',
  'rodrigo da silva graciano|wellington carvalho',
  'rodrigo de oliveira silva|11',
  'rodrigo de souza zaneti|murilo chiachio santiago',
  'rodrigo ferrarezi|rafael kanashiro',
  'rodrigo nacarato scazufca stenico|vinicius semeride francini',
  'rodrigo silva dos santos|abraão lima velozo',
  'rogério aprobato|laura galvão',
  'rogério batista montenegro|diego perissinotto',
  'rohrist christian souza silva|laura galvão',
  'roque francisco pacheco junior|leonardo barroso',
  'rosa elena de lima camargo|não',
  'rosangela dos santos de oliveira|marcelo ferreira rodrigues',
  'rosemeire alves pereira|9',
  'rosemeire geronimo sobral sacamoto|gustavo gomes da silva',
  'rosiane amorim andrade|gabriel braga',
  'rosimare rosa julião|leonardo barroso',
  'ruan santos de paulo|raphael gonçalves teixeira',
  'rubens borges medeiros de miranda|gabriel bueno de melo serrano',
  'salatiel costa farias|elisa cardoso',
  'samuel foelkel savietto|mateus savietto',
  'samuel silva|lucca de lauro',
  'samuel teixeira de abreu filho|joão pedro lotti jardim',
  'sandra cristina dos santos|laura galvão',
  'sandra lenhate dos santos|thamires furlan',
  'sandro sérgio muniz da silva|nathaliê melo',
  'sara beatriz hack|murilo chiachio santiago',
  'sara maria freitas de almeida|raphael gonçalves teixeira',
  'saulo de oliveira machado|fernando bizelli',
  'saulo zen fonseca|matheus okamura lopes',
  'scarlett carvalho nabuco d''ávila cespedes|fernando bizelli',
  'scheila pereira ficagna|maria vitória ferreira cotrim',
  'sergio lopes|elisa cardoso',
  'sergio vinicius massarolo dias|maria vitória ferreira cotrim',
  'sheyla rocha rohnelt baraldo|bianca sara garcia onaga',
  'silvio amaro soares teixeira|marcelo ferreira rodrigues',
  'silvio matheus de medeiros siuta|bianca sara garcia onaga',
  'simone martins soares prezia|andre luiz soares prezia',
  'stefany de souza alves|matheus lenci',
  'stella clemente da silva|francisco rivera',
  'stella maria santos michelon|diego perissinotto',
  'stephanie raira gonçalves|matheus okamura lopes',
  'stephannie caroline esper maziero|lucca de lauro',
  'stéfanie heliodora lourenço|thiago cunha',
  'suellen silvia machado|12',
  'tainara correia rodrigues|abraão lima velozo',
  'tainá dione de abrantes bastos do nascimento|marcelo ferreira rodrigues',
  'tainá vieira da silva|francine santos',
  'tais fernandes velleca|francisco rivera',
  'taisi lima da cruz|emmanuel costa',
  'taisy machado silva|rafael kanashiro',
  'talita benazzi de andrade|felipe youssef helal',
  'talita pignato aragão|francine santos',
  'talita silva chaves|felipe marques matias',
  'talitha albuquerque cajal teixeira corder|caio bragança',
  'talmom gabriel bernardes|felipe youssef helal',
  'tatiana soares da silva skiavine|fabrício viana',
  'tatiane alves uechi motoyama|8',
  'tatiane cristina dos santos|pedro ivo teixeira',
  'tayna magalhaes ferreira|wellington carvalho',
  'tayna teodoro da silva de oliveira|vinicius semeride francini',
  'tayse ubríaco|raphael gonçalves teixeira',
  'taís krauss pinto toledo|felipe youssef helal',
  'thais aparecida macedo batista|francine santos',
  'thais castro nunes|joão pedro lotti jardim',
  'thais cavalcanti oliveira da silva|leonardo barroso',
  'thais graziella souza barbosa|joão pedro lotti jardim',
  'thais kwiatkowski da silva|gustavo machado',
  'thais santos rossi|fabrício viana',
  'thamires saraiva xavier|mariana cruz',
  'thatiane oliveira tavares|gabriel baptista',
  'thauany schaefer|thiago cunha',
  'thaynara de jesus da luz santos|fabrício viana',
  'thaís zago machado morato|leonardo barroso',
  'thiago alves de souza|lucca de lauro',
  'thiago bogoni spindola|nathaliê melo',
  'thiago da silva teixeira|raphael gonçalves teixeira',
  'thiago duarte|francisco rivera',
  'thiago henrique bueno vaz|samuel teixeira',
  'thiago mendonça de vasconcelos|maria vitória ferreira cotrim',
  'thiago pineiro bizelli|fernando bizelli',
  'thiago rodrigues da silva|marcelo ferreira rodrigues',
  'thuany carolina de azevedo|maria vitória ferreira cotrim',
  'thulio mendonça teixeira|murilo chiachio santiago',
  'tiago de oliveira|diego perissinotto',
  'tiago henrique vieira da silva|andre luiz soares prezia',
  'tábata rodrigues de souza|caio bragança',
  'valdir josé alves casotti barbosa|hélio brollo junior',
  'valquíria crivelaro|leonardo rossetti',
  'vanessa fernandes alves reis|wellington carvalho',
  'vanessa gomulski carcaioli|francisco rivera',
  'vanessa gonçalves castilhano|diego perissinotto',
  'venício de vargas vefago|andre luiz soares prezia',
  'verônica corrêa cesar rodrigues|leonardo barroso',
  'verônica maria tavares de almeida desiderio|gabriel baptista',
  'victor alexandre moro valentim|gustavo machado',
  'victor aparecido martins macedo da silva|felipe youssef helal',
  'victor henry de wit janssen|gustavo gomes da silva',
  'victor hugo buffon|elisa cardoso',
  'victor hugo da cruz lima|leonardo barroso',
  'victor hugo dos santos brito|13',
  'victor pardinho da rocha|mariana cruz',
  'victor vieira dos santos|wellington carvalho',
  'victoria soares tiba|joão pedro lotti jardim',
  'vilma alves ramalho|gabriel baptista',
  'vilmar bernardes júnior|francine santos',
  'vinicius de almeida novaes|murilo chiachio santiago',
  'vinicius oliveira nascimento louro|thiago cunha',
  'vinicius oliveira pierine|andre luiz soares prezia',
  'vinicius ragnini da silva|munir mustafa',
  'vinicius tsutomu tome harada|nathaliê melo',
  'vinícius pereira de souza|maria vitória ferreira cotrim',
  'vitor alves franco lopes|pedro ivo teixeira',
  'vitor da silva alves|mariana cruz',
  'vitor guimarães|fernando bizelli',
  'vitor hugo euripedes de souza alves|mariana cruz',
  'vitor prado montemor|gustavo gomes da silva',
  'vitoria ribeiro alves|mariana cruz',
  'vitoria souza soares|matheus lenci',
  'vitória augustus fernandes barboza|maria vitória ferreira cotrim',
  'vitória dos santos carvalho junqueira|12',
  'viviane bezerra da silva|leonardo rossetti',
  'viviane palma capuano|maria vitória ferreira cotrim',
  'vivianne curvo de galitzki|abraão lima velozo',
  'wagner ribeiro rosa junior|gustavo gomes da silva',
  'wanessa cordeiro nascimento domingues|mariana cruz',
  'washington igor dos santos silva|abraão lima velozo',
  'weskley jakson pereira|leonardo barroso',
  'wesley silva marins|francine santos',
  'yago monteiro da cunha|matheus lenci',
  'yanca sabrina iozzi|6',
  'yasmin trioni machado ganzaroli|bianca sara garcia onaga',
  'ygor lourenço freires|murilo chiachio santiago',
  'yuri colombo|joão pedro lotti jardim',
  'éder frança da costa|gustavo gomes da silva',
  'évellin haidê ramalho martins|gabriel baptista'
]) AS key
WHERE NOT EXISTS (
  SELECT 1 FROM clients c
  WHERE LOWER(TRIM(c.name)) || '|' || LOWER(TRIM(c.planner)) = key
    AND c.name != '0'
    AND c.planner != '0'
)
ORDER BY key;